### ISSUE TITLE
Version 1.4.0: System.Exception: '/licenses[302]/isFsfLibre' is missing

### ISSUE THREAD

**Issue by ml-eds** [aaronpowell/dotnet-delice#14]
Hello,

I get the error message below when executing dotnet-delice

Version 1.4.0
OS: MacOS 10.14.6
Dotnet Version: .NET Core SDK (3.1.100)
The processed project is for .Net Core 3

```
Unhandled exception. System.Exception: '/licenses[302]/isFsfLibre' is missing
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Output.getSpdxInfo@39-1.Invoke(IJsonDocument _arg1) in /home/vsts/work/1/s/src/DotNetDelice/Output.fs:line 40
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Spdx.getSpdx@39-10.Invoke(AsyncActivation`1 ctxt) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/Spdx.fs:line 39
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at ConsoleOutput.prettyPrint@75-11.Invoke(Tuple`2 tupledArg) in /home/vsts/work/1/s/src/DotNetDelice/ConsoleOutput.fs:line 81
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 494
   at ConsoleOutput.prettyPrint(String name, IEnumerable`1 licenses) in /home/vsts/work/1/s/src/DotNetDelice/ConsoleOutput.fs:line 94
   at App.OnExecute@109-2.Invoke(PackageSpec projectSpec) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 111
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at App.Cli.OnExecute() in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 9
Abort trap: 6
```

**Comment by ml-eds** [comment]
I do a simple `dotnet-delice projectname.csproj` call.

**Comment by ml-eds** [comment]
Could the Windows file path `E:\A\_work\130\s\src\fsharp\FSharp.Core` be the problem?

**Comment by aaronpowell** [comment]
That path is the path that `FSharp.Core` was compiled on by its build server and since everything has source-link setup we can get decent debugging info (which is why you see some *Nix paths in there, as my build agent is a Linux server).

Back to the error, I've not been able to repo it on Windows or Linux but the problem it's referring to is that one of the licenses from `https://spdx.org/licenses/licenses.json` is missing a property that the JSON provider expects (`isFsfLibre`) but that shouldn't matter as missing fields become `Option<'T>`.

Are you still experiencing it?

**Comment by ml-eds** [comment]
Yes, the error is still ocurring. 

I can confirm that the `isFsLibre` attribute is missing at the index (302) mentioned in the exception message.

<img width="598" alt="Bildschirmfoto 2020-02-21 um 08 42 52" src="https://user-images.githubusercontent.com/35484461/75014384-6da37080-5486-11ea-8a44-504a0f6d7e1e.png">

**Comment by Crydsch** [comment]
I encountered this error too.

Version 1.4.0
OS: Windows 10.0.18362
Dotnet Version: .NET Core SDK (3.1.101)
The processed project is for .Net Core 3.1

`Unhandled exception. System.Exception: '/licenses[37]/isFsfLibre' is missing`

**Comment by phillip-haydon** [comment]
I'm also getting this error on a .net core 3.1 project. 

```
Unhandled exception. System.Exception: '/licenses[308]/isFsfLibre' is missing
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Output.getSpdxInfo@39-1.Invoke(IJsonDocument _arg1) in /home/vsts/work/1/s/src/DotNetDelice/Output.fs:line 40
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at Spdx.getSpdx@39-10.Invoke(AsyncActivation`1 ctxt) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/Spdx.fs:line 39
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 350
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 882
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1154
   at ConsoleOutput.prettyPrint@75-11.Invoke(Tuple`2 tupledArg) in /home/vsts/work/1/s/src/DotNetDelice/ConsoleOutput.fs:line 81
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 78
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 64
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 494
   at ConsoleOutput.prettyPrint(String name, IEnumerable`1 licenses) in /home/vsts/work/1/s/src/DotNetDelice/ConsoleOutput.fs:line 94
   at App.OnExecute@109-2.Invoke(PackageSpec projectSpec) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 111
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at App.Cli.OnExecute() in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 9
```

**Comment by aaronpowell** [comment]
I've changed how the JSON is parsed by the type provider so that the `isFsfLibre` field is now `Option<bool>` which should fix this.

Grab the update of `1.5.0` and let me know if it works.

**Comment by phillip-haydon** [comment]
:+1: it ran perfectly without issue. Thanks a lot!

**Comment by ml-eds** [comment]
Yes! It works! Thank you very much!
