### ISSUE TITLE
Exception thrown when running against .csproj

### ISSUE THREAD

**Issue by rjherman2011** [aaronpowell/dotnet-delice#18]
Getting the following exception when running against my .csproj file:

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at App.OnExecute@76-2.Invoke(PackageSpec projectSpec) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 77
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 7

**Comment by phillip-haydon** [comment]
I'm also getting this error when running against a .NET 4.8 project.

**Comment by aaronpowell** [comment]
Unfortunately, I'm unable to support .NET Framework, only .NET Core. I've release 1.5.0 which does a better job of error handling of this though.
