### ISSUE TITLE
Getting a weird System.IO.FileNotFound-Exception when using fitsharp Nuget package

### ISSUE THREAD

**Issue by McTristan** [aaronpowell/dotnet-delice#20]
I get a weird FileNotFoundException and I'm not sure if a) this should really happen and b) while there is a file license.txt in the license subfolder of the package it can't find it. 

I've tried it on linux and I guess the path is kind of weird - it is using backslashes and slashes while it should use either one (slashes in my case).

` Unhandled exception. System.IO.FileNotFoundException: Could not find file '/root/.nuget/packages/fitsharp/2.8.1/license\license.txt'.
 File name: '/root/.nuget/packages/fitsharp/2.8.1/license\license.txt'
    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
    at LicenseBuilder.buildLicenseFromPackage(Boolean checkGitHub, String token, FSharpFunc`2 checkLicenseContents', PackageIdentity identity, String packagePath, LocalPackageInfo pId, String path) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/LicenseBuilder.fs:line 45
    at App.getLicenses@44.Invoke(LockFileLibrary lib) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 45
    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 81
    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 68
    at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 178
    at Microsoft.FSharp.Collections.Internal.IEnumerator.next@193[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 194
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
    at Microsoft.FSharp.Collections.SeqModule.SortBy@1105.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 1108
    at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@469.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 469
    at Microsoft.FSharp.Collections.SeqModule.Length[T](IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 716
    at JsonOutput.jsonBuilder(String name, IEnumerable`1 licenses) in /home/vsts/work/1/s/src/DotNetDelice/JsonOutput.fs:line 68
    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 81
    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 68
    at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@418-1.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 422
    at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 322
    at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
    at JsonOutput.jsonPrinter(String path, IEnumerable`1 json) in /home/vsts/work/1/s/src/DotNetDelice/JsonOutput.fs:line 99
 --- End of stack trace from previous location where exception was thrown ---
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 9`

**Comment by aaronpowell** [comment]
It looks like that with fitsharp the license file is embedded in the nuspec but uses Windows paths to the file (https://github.com/jediwhale/fitsharp/blob/2.8.1/nuget/FitSharp.nuspec#L14).

I've fixed this in https://github.com/aaronpowell/dotnet-delice/commit/e4bc6b0a011abaa85421f64163e81bb74d865751 and that'll roll out in release 1.5.1 tonight.

**Comment by aaronpowell** [comment]
As a side note, the library is dual-licensed, which is hard to detect from the file (the dice coefficient thinks it's just GPL) and I don't believe the nuspec has any way to indicate dual-licensing.

**Comment by aaronpowell** [comment]
1.5.1 is on NuGet, let me know if it fixes it for you.

**Comment by McTristan** [comment]
Thank you! Yes this one is fixed but I get another error:

Unhandled exception. System.Net.WebException: The remote server returned an error: (404) Not Found.
 Response from https://api.github.com/repos/CharsetDetector/UTF-unknown/license:
 {"message":"Not Found","documentation_url":"https://developer.github.com/v3/licenses/#get-the-contents-of-a-repositorys-license"}
  ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
    at FSharp.Data.HttpHelpers.getResponseAsync@1319-4.Invoke(Exception _arg2)
    at <StartupCode$FSharp-Core>.$Async.TryWith@1082-1.Invoke(Exception exn) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1082
    at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 catchFilter, ExceptionDispatchInfo edi) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 436
    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
    --- End of inner exception stack trace ---
    at FSharp.Data.HttpHelpers.augmentWebExceptionsWithDetails@1227-3.Invoke(Unit unitVar)
    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
    at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@589.Invoke(AsyncActivation`1 ctxt) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 589
    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
 --- End of stack trace from previous location where exception was thrown ---
    at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 351
    at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 882
    at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
    at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1154
    at LicenseCache.checkLicenseViaGitHub$cont@197(String token, String licenseUrl, Group repoGroup, Group orgGroup, Unit unitVar) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/LicenseCache.fs:line 208
    at LicenseCache.checkLicenseViaGitHub(String token, String licenseUrl) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/LicenseCache.fs:line 221
    at LicenseBuilder.buildLicenseFromPackage$cont@55(Boolean checkGitHub, String token, FSharpFunc`2 checkLicenseContents', PackageIdentity identity, LocalPackageInfo pId, LicenseMetadata licenseMetadata, Unit unitVar) in /home/vsts/work/1/s/src/DotNetDelice.Licensing/LicenseBuilder.fs:line 58
    at App.getLicenses@44.Invoke(LockFileLibrary lib) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 45
    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 81
    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 68
    at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@171.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 178
    at Microsoft.FSharp.Collections.Internal.IEnumerator.next@193[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 194
    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
    at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
    at Microsoft.FSharp.Collections.SeqModule.SortBy@1105.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 1108
    at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@469.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 469
    at Microsoft.FSharp.Collections.SeqModule.Length[T](IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 716
    at JsonOutput.jsonBuilder(String name, IEnumerable`1 licenses) in /home/vsts/work/1/s/src/DotNetDelice/JsonOutput.fs:line 68
    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 81
    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 68
    at Microsoft.FSharp.Collections.Generator.Microsoft-FSharp-Collections-Generator-Generator-1-get_Apply@418-1.Invoke(Unit unitVar0) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 422
    at Microsoft.FSharp.Collections.Generator.appG[a](Generator`1 g) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 322
    at Microsoft.FSharp.Collections.Generator.EnumeratorWrappingLazyGenerator`1.System-Collections-IEnumerator-MoveNext()
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
    at JsonOutput.jsonPrinter(String path, IEnumerable`1 json) in /home/vsts/work/1/s/src/DotNetDelice/JsonOutput.fs:line 99
 --- End of stack trace from previous location where exception was thrown ---
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 9



This time it is trying to load a license via github which produces a 404 error - would be great to have a way to ignore/allow such errors and/or a fallback solution.

https://api.github.com/repos/CharsetDetector/UTF-unknown shows "null" in the license field so I think it shouldn't try to check the license at all?!

Should I create a new issue?

**Comment by aaronpowell** [comment]
Yep, create it as a new issue, so I can do a resolution against the correct one.

But it looks like I was just lazy on the error handling and not expecting a 404 from the license response
