### ISSUE TITLE
Multiple sln's in folder triggers exception

### ISSUE THREAD

**Issue by Jogai** [aaronpowell/dotnet-delice#4]
```
Unhandled Exception: System.Exception: More than one solution file found in the path
   at App.findProject(String path) in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 22
   at App.Cli.OnExecute() in /home/vsts/work/1/s/src/DotNetDelice/App.fs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at Program.main(String[] args) in /home/vsts/work/1/s/src/DotNetDelice/Program.fs:line 7
```

Supplying the sln file just gives me "whoops". My project is regular .net 4, is this only meant for core projects?

**Comment by aaronpowell** [comment]
`delice` only supports the new .NET project format and projects that can be compiled with the dotnet cli, not .NET Framework projects.

I should get around to fixing the error message when it fails to build the dependency graph (rather than `whoops`), but that's an edge condition that should rarely get hit.
